### PR TITLE
Support non-English characters

### LINKED ISSUE #9: Doesn't seem to support non-English characters
2021-01-09T11:12+01:00

Looking at the screenshot, it would be expected that "felfüggesztette" would show up in the suggestions, but it doesn't. Words that only contain characters also present in the English alphabet word fine, for example Twitter, tesztre, azokat, etc.

### PR DESCRIPTION
**Pull request by kantord**
fix #9

### CODE REVIEW

**Comment by kantord** [comment]
I'm not sure how to test it, so I haven't tested it in the browser, but I've tested the regexp itself.

2021-01-09T11:33+01:00

**Comment by kantord** [comment]
Also not sure if it could be somehow extended to languages that don't need to put non-word characters between words

**Comment by voldikss** [comment]
Hi @kantord thanks for this but I feel that this would make it more disturbing for completion.

Because I am a chinese, the regex in the patch will grab all the chinese characters, which are not what we want. 

image

**Comment by kantord** [comment]
What would be the expected behavior for Chinese text?

**Comment by voldikss** [comment]
Chinese text should not be grabbed as it is too disturbing

**Comment by voldikss** [comment]
Actually East Asian people like us usually doesn't use completion from their native language text.

**Comment by kantord** [comment]
So to understand better: your ideal use case is grabbing completion only from source code? Or is it: only source code + text in foreign languages?

If it's more about code then perhaps it's possible to only enable completion from the `<code />` html tag.

Or perhaps also stuff like code review threads on GitHub/GitLab

**Comment by voldikss** [comment]
> So to understand better: your ideal use case is grabbing completion only from source code?

No matter whether from souce code. What I originally want is to grab English words for completion. The language words in your screenshot is also acceptable, but your regular expression doesn't filter out east-asian characters.

**Comment by kantord** [comment]
Technically it's possible to filter out only certain scripts. For example the Unicode property `Latn` will only include characters from the Latin script, what do you think?

TBH it's not a big deal for me either, as my main use case is autocompletion from pull requests and other English text, I just noticed by accident that certain characters are not supported

**Comment by voldikss** [comment]
I feel that this is useful sometime but maybe English words completion is sufficient. I tend to not include this feature, what's your thoughts?

**Comment by kantord** [comment]
yup, that makes sense

**Pull request closed without merging**
